# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
r:
  - release
  - devel
  - oldrel
os:
  - linux
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'

