# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
r:
  - release
  - devel
  - oldrel
os:
  - linux
warnings_are_errors: false
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo ldconfig
r_packages:
  - lwgeom
  - rgdal
after_success:
  - Rscript -e 'covr::codecov()'

