# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
r:
  - release
  - devel
  - oldrel
warnings_are_errors: false
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
after_success:
  - Rscript -e 'covr::codecov()'

